#!/bin/bash

#############################################################
# Supabase Auth Setup Script
# 
# This script safely configures your Supabase authentication
# using credentials from supabase-credentials.env
#############################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${CYAN}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Header
echo ""
echo "================================================"
echo "   Supabase Authentication Setup"
echo "================================================"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    print_error "Please run this script from the web-partner directory"
    echo "Run: cd /Users/chromefang.exe/HobbyistSwiftUI/web-partner"
    exit 1
fi

# Step 1: Check for credentials file
print_status "Checking for credentials file..."

if [ ! -f "supabase-credentials.env" ]; then
    print_warning "supabase-credentials.env not found!"
    echo ""
    echo "Please follow these steps:"
    echo "1. Copy the template file:"
    echo "   cp supabase-credentials.template supabase-credentials.env"
    echo ""
    echo "2. Edit the file and add your Supabase credentials:"
    echo "   nano supabase-credentials.env"
    echo ""
    echo "3. Run this script again:"
    echo "   ./setup-supabase-auth.sh"
    echo ""
    
    # Offer to create it now
    read -p "Would you like to create supabase-credentials.env now? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cp supabase-credentials.template supabase-credentials.env
        print_success "Created supabase-credentials.env"
        echo ""
        echo "Please edit it with your credentials:"
        echo "  nano supabase-credentials.env"
        echo ""
        echo "Then run this script again."
    fi
    exit 1
fi

print_success "Found supabase-credentials.env"

# Step 2: Source the credentials
print_status "Loading credentials..."
source supabase-credentials.env

# Step 3: Validate required fields
if [ -z "$SUPABASE_URL" ] || [ "$SUPABASE_URL" = "your_project_url_here" ]; then
    print_error "SUPABASE_URL is not set in supabase-credentials.env"
    echo "Please add your Supabase project URL"
    exit 1
fi

if [ -z "$SUPABASE_ANON_KEY" ] || [ "$SUPABASE_ANON_KEY" = "your_anon_key_here" ]; then
    print_error "SUPABASE_ANON_KEY is not set in supabase-credentials.env"
    echo "Please add your Supabase anon/public key"
    exit 1
fi

print_success "Credentials validated"

# Step 4: Create .env.local
print_status "Creating .env.local file..."

cat > .env.local << EOF
# Supabase Configuration
# Generated by setup-supabase-auth.sh
# Last updated: $(date)

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

# OAuth Providers (if configured)
EOF

# Add OAuth credentials if provided
if [ ! -z "$GOOGLE_CLIENT_ID" ]; then
    echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env.local
    echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> .env.local
    print_success "Google OAuth configured"
fi

if [ ! -z "$APPLE_CLIENT_ID" ]; then
    echo "NEXT_PUBLIC_APPLE_CLIENT_ID=${APPLE_CLIENT_ID}" >> .env.local
    echo "APPLE_TEAM_ID=${APPLE_TEAM_ID}" >> .env.local
    echo "APPLE_KEY_ID=${APPLE_KEY_ID}" >> .env.local
    print_success "Apple OAuth configured"
fi

if [ ! -z "$FACEBOOK_APP_ID" ]; then
    echo "NEXT_PUBLIC_FACEBOOK_APP_ID=${FACEBOOK_APP_ID}" >> .env.local
    echo "FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}" >> .env.local
    print_success "Facebook OAuth configured"
fi

print_success ".env.local created successfully"

# Step 5: Update .gitignore
print_status "Updating .gitignore..."

# Check if credentials file is in gitignore
if ! grep -q "supabase-credentials.env" .gitignore 2>/dev/null; then
    echo "" >> .gitignore
    echo "# Supabase credentials (never commit!)" >> .gitignore
    echo "supabase-credentials.env" >> .gitignore
    echo ".env.local" >> .gitignore
    print_success "Added credentials to .gitignore"
else
    print_success ".gitignore already configured"
fi

# Step 6: Install dependencies
print_status "Installing dependencies..."
npm install
print_success "Dependencies installed"

# Step 7: Show next steps
echo ""
echo "================================================"
echo "   Setup Complete! 🎉"
echo "================================================"
echo ""
print_success "Your Supabase authentication is configured!"
echo ""
echo "Next steps:"
echo "1. Configure authentication in Supabase Dashboard:"
echo "   ${CYAN}${SUPABASE_URL}${NC}"
echo ""
echo "2. Enable Email authentication:"
echo "   - Go to Authentication → Providers"
echo "   - Enable Email provider"
echo ""
echo "3. Add redirect URLs:"
echo "   - Go to Authentication → URL Configuration"
echo "   - Add: http://localhost:3000/auth/callback"
echo ""
echo "4. Start the development server:"
echo "   ${GREEN}npm run dev${NC}"
echo ""
echo "5. Open in browser:"
echo "   ${CYAN}http://localhost:3000${NC}"
echo ""

# Offer to start the dev server
read -p "Would you like to start the development server now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    print_status "Starting development server..."
    npm run dev
fi