#!/bin/bash

echo "🚀 Testing New Webhook Deployment"
echo "=================================="
echo ""
echo "Wait 2-3 minutes for Vercel to deploy, then:"
echo ""
echo "1. Trigger test event:"
echo "   stripe trigger payment_intent.succeeded"
echo ""
echo "2. Check Vercel logs for:"
echo "   Look for: '🎯 [NEW DEPLOYMENT] Payment succeeded'"
echo "   If you see this → new code is running!"
echo ""
echo "3. Should also see:"
echo "   '✅ Payment event recorded in database'"
echo ""
echo "4. Verify in database:"
echo "   SELECT COUNT(*) FROM stripe_payment_events;"
echo "   Should be > 0"
echo ""
echo "5. Check details:"
echo "   SELECT * FROM stripe_payment_events ORDER BY created_at DESC LIMIT 1;"
echo ""
echo "=================================="
echo "Deployment commit: e2fe9d2"
echo "Check deployment status: https://vercel.com/dashboard"
echo ""
