#!/bin/bash

# Fix Release Build Settings for App Store Distribution
# This script optimizes the build settings for App Store submission

set -e

echo "🔧 Fixing Release Build Settings for App Store Distribution"
echo "==========================================================="

# Set proper Swift optimization level for Release
echo "Setting Swift Optimization Level to -O (Release optimization)..."
/usr/libexec/PlistBuddy -c "Set :objects:7A1234511234567890ABCDEF:buildConfigurationList:configurations:1:buildSettings:SWIFT_OPTIMIZATION_LEVEL -O" HobbyistSwiftUI.xcodeproj/project.pbxproj 2>/dev/null || echo "Setting Swift optimization in xcconfig..."

# Use xcodebuild to set the build settings properly
echo "Configuring build settings via xcodebuild..."

# Update the project file directly using xcconfig approach
cat > Release.xcconfig << EOF
// Release Configuration for App Store Distribution
// Auto-generated by fix-release-settings.sh

// Swift Optimization
SWIFT_OPTIMIZATION_LEVEL = -O
SWIFT_COMPILATION_MODE = wholemodule

// GCC/Clang Optimization  
GCC_OPTIMIZATION_LEVEL = s
DEPLOYMENT_POSTPROCESSING = YES

// Code Signing for Distribution
CODE_SIGN_STYLE = Automatic
DEVELOPMENT_TEAM = 594BDWKT53

// Bitcode (disabled as per Apple requirements)
ENABLE_BITCODE = NO

// Debug Information
DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
GCC_GENERATE_DEBUGGING_SYMBOLS = YES

// App Store Requirements
ASSETCATALOG_COMPILER_GENERATE_SWIFT_SYMBOLS = YES
VALIDATE_PRODUCT = YES

// Performance Settings
COPY_PHASE_STRIP = YES
GCC_PREPROCESSOR_DEFINITIONS = RELEASE=1

EOF

echo "✅ Release.xcconfig created with optimized settings"
echo ""
echo "⚠️  To apply these settings, you need to:"
echo "1. Open Xcode"
echo "2. Go to Project Settings > HobbyistSwiftUI > Configurations"
echo "3. Set Release configuration to use Release.xcconfig"
echo ""
echo "Or run the archive command with explicit build settings:"

ARCHIVE_PATH="./build/HobbyistSwiftUI_v1.0_b2.xcarchive"

echo ""
echo "🚀 Optimized Archive Command:"
echo "============================="
echo "xcodebuild archive \\"
echo "    -scheme HobbyistSwiftUI \\"
echo "    -configuration Release \\"
echo "    -destination 'generic/platform=iOS' \\"
echo "    -archivePath \"$ARCHIVE_PATH\" \\"
echo "    CODE_SIGN_STYLE=Automatic \\"
echo "    DEVELOPMENT_TEAM=594BDWKT53 \\"
echo "    SWIFT_OPTIMIZATION_LEVEL=-O \\"
echo "    GCC_OPTIMIZATION_LEVEL=s \\"
echo "    SWIFT_COMPILATION_MODE=wholemodule"
echo ""

echo "✅ Build settings optimization complete!"