// Shared types for class management system

export interface Class {
  id: string;
  name: string;
  description: string;
  instructor: string;
  instructorId: string;
  category: string;
  level: 'beginner' | 'intermediate' | 'advanced';
  duration: number;
  capacity: number;
  price: number;
  creditCost: number;
  image: string;
  tags: string[];
  location: string;
  status: 'active' | 'inactive' | 'draft';
  rating: number;
  totalBookings: number;
  nextSession?: {
    date: string;
    time: string;
    spots: number;
  };
}

export interface Student {
  id: string;
  name: string;
  email: string;
  phone?: string;
  joinDate: string;
  totalClasses: number;
  creditsBalance: number;
  preferredContact: 'email' | 'sms' | 'phone';
  notes?: string;
}

export interface BookingDetails {
  id: string;
  studentId: string;
  student: Student;
  bookingDate: string;
  paymentStatus: 'paid' | 'pending' | 'refunded' | 'failed';
  paymentMethod: 'credits' | 'cash' | 'card' | 'free';
  amount: number;
  transactionId?: string;
  notes?: string;
  source: 'app' | 'web' | 'phone' | 'walkIn';
  confirmationSent: boolean;
  reminderSent: boolean;
  status: 'confirmed' | 'pending' | 'cancelled' | 'noShow';
}

export interface WaitlistEntry {
  id: string;
  studentId: string;
  student: Student;
  addedDate: string;
  position: number;
  autoEnroll: boolean;
  maxPrice?: number;
  notes?: string;
  notificationsSent: number;
}

export interface ClassSession {
  id: string;
  classId: string;
  className: string;
  instructor: string;
  instructorId: string;
  date: string;
  startTime: string;
  endTime: string;
  duration: number;
  capacity: number;
  enrolled: number;
  waitlist: number;
  price: number;
  creditCost: number;
  location: string;
  status: 'scheduled' | 'completed' | 'cancelled' | 'in-progress';
  bookings: BookingDetails[];
  waitlistEntries?: WaitlistEntry[];
  revenue: number;
  expenses?: number;
  profitMargin?: number;
  lastUpdated?: string;
}

export interface Instructor {
  id: string;
  name: string;
  email: string;
  phone?: string;
  profileImage?: string;
  specialties: string[];
  yearsExperience: number;
  rating: number;
  totalClasses: number;
  totalRevenue: number;
  status: 'active' | 'inactive' | 'on-leave';
  joinDate: string;
  hourlyRate: number;
  commissionRate: number;
  availability: {
    [key: string]: {
      available: boolean;
      startTime?: string;
      endTime?: string;
      notes?: string;
    };
  };
  certifications: string[];
  bio: string;
  languages: string[];
  preferredClassTypes: string[];
  maxClassesPerDay: number;
  notificationPreferences: {
    email: boolean;
    sms: boolean;
    push: boolean;
  };
}

export interface ClassAssignment {
  id: string;
  classId: string;
  className: string;
  instructorId: string;
  date: string;
  startTime: string;
  endTime: string;
  status: 'assigned' | 'confirmed' | 'completed' | 'cancelled';
  students: number;
  capacity: number;
  revenue: number;
  instructorPayout: number;
  location: string;
  notes?: string;
  substitutes?: string[];
}

export interface ClassTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  level: 'beginner' | 'intermediate' | 'advanced';
  duration: number;
  capacity: number;
  price: number;
  creditCost: number;
  location: string;
  instructorId?: string;
  instructorName?: string;
  materials: string[];
  prerequisites: string[];
  tags: string[];
  image?: string;
  status: 'active' | 'inactive' | 'draft';
  createdDate: string;
  lastUsed?: string;
  timesUsed: number;
}

export interface RecurrenceRule {
  id: string;
  templateId: string;
  frequency: 'daily' | 'weekly' | 'monthly';
  interval: number;
  daysOfWeek?: number[];
  dayOfMonth?: number;
  startDate: string;
  endDate?: string;
  maxOccurrences?: number;
  startTime: string;
  endTime: string;
  exceptions: string[];
  generateAhead: number;
  autoConfirm: boolean;
  requireInstructorConfirmation: boolean;
  status: 'active' | 'paused' | 'completed';
  createdDate: string;
  lastGenerated?: string;
  nextGeneration?: string;
  totalGenerated: number;
}

export interface GeneratedSession {
  id: string;
  templateId: string;
  recurrenceRuleId: string;
  className: string;
  date: string;
  startTime: string;
  endTime: string;
  instructorId?: string;
  status: 'scheduled' | 'confirmed' | 'cancelled' | 'completed';
  enrolled: number;
  capacity: number;
  revenue: number;
  generatedDate: string;
  autoGenerated: boolean;
}

// Component Props Types
export interface ClassScheduleProps {
  classes: Class[];
  onClose: () => void;
  onSave?: (scheduleData: any) => void;
}

export interface SessionManagementProps {
  session: ClassSession;
  onClose: () => void;
  onUpdateSession: (session: ClassSession) => void;
}

export interface InstructorAssignmentProps {
  onClose: () => void;
  onSave?: (assignments: ClassAssignment[]) => void;
}

export interface RecurringTemplatesProps {
  onClose: () => void;
  onSave?: (templates: ClassTemplate[], rules: RecurrenceRule[]) => void;
}

// Utility Types
export type SessionStatus = ClassSession['status'];
export type PaymentMethod = BookingDetails['paymentMethod'];
export type PaymentStatus = BookingDetails['paymentStatus'];
export type BookingSource = BookingDetails['source'];
export type InstructorStatus = Instructor['status'];
export type ClassLevel = Class['level'];
export type RecurrenceFrequency = RecurrenceRule['frequency'];